title: "Jack Hamond's Site"
description: 
url: "https://jackhamond.github.io"
baseurl: ""
markdown: kramdown
theme: null
header-image: "/assets/media/images/iesu, maria, ioseph!.png"

collections:
  poems:
    output: true
    permalink: /research/poems/:name/
  recipes:
    output: true
    permalink: /research/recipes/:name/
    
